config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_out: 'logout'}

  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :pessoa_juridicas
  resources :atrativos do
    post 'cadastrar_entradas'
  end
  resources :funcionarios do
    get 'toggleActiveStatus', on: :member
  end

end

app/models/atrativo.rb
class Atrativo < ApplicationRecord
  has_one_attached :imagem
  has_many :registro_venda_ingressos, :class_name => 'RegistroVendaIngressos'

  belongs_to :pessoa_juridica

  register_currency :brl
  monetize :valorIngressoAdultoCentavos, as: 'valor_ingresso_adulto', numericality: {
      greater_than_or_equal_to: 0}
  monetize :valorIngressoCriancaCentavos, as: 'valor_ingresso_crianca', numericality: {
      greater_than_or_equal_to: 0,
  }

  validates :nome, presence: true
  validates :endereco, presence: true
  validates :tempoDuracaoMinutos, presence: true
  validates :capacidadeMaximaPessoas, presence: true
  validates :valorIngressoAdultoCentavos, presence: true
  validates :valorIngressoCriancaCentavos, presence: true

  monetize :valor_total_arrecadado_centavos, as: 'valor_total_arrecadado'

  # scope :this_months_event, lambda { where("start_at >= ? AND start_at <= ?",
  #                                          Time.zone.now.beginning_of_month, Time.zone.now.end_of_month) }

  def get_registros_venda_ingressos_mes_atual
    self.registro_venda_ingressos.where("created_at >= ? and created_at <= ?",
                                        Date.current.beginning_of_month,
                                        Date.current.end_of_month)
  end

  def get_numero_ingressos_vendidos(somente_mes_atual = false)
    registros_venda_ingressos = somente_mes_atual ? self.get_registros_venda_ingressos_mes_atual : self.registro_venda_ingressos

    total_pessoas = 0

    for registro in registros_venda_ingressos
      total_pessoas += (registro.numeroCriancas + registro.numeroAdultos)
    end

    total_pessoas
  end

  def valor_total_arrecadado_centavos(somente_mes_atual = false)
    registros_venda_ingressos = somente_mes_atual ? self.get_registros_venda_ingressos_mes_atual : self.registro_venda_ingressos

    total_arrecadado = 0

    for registro in registros_venda_ingressos
      total_arrecadado += ((registro.numeroCriancas * registro.valorIngressoCriancaCentavos) + (registro.numeroAdultos * registro.valorIngressoAdultoCentavos))
    end

    total_arrecadado
  end
end

app/controllers/atrativos_controller.rb
class AtrativosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_atrativo, only: [:show, :edit, :update, :destroy]
  before_action :check_admin_access, only: [:new, :create, :destroy]

  # GET /atrativos
  def index
    @pessoa_juridica = current_user.pessoa_juridica
    @atrativos = @pessoa_juridica.atrativos
  end

  # GET /atrativos/1
  # GET /atrativos/1.json
  def show
  end

  # GET /atrativos/new
  def new
    @atrativo = Atrativo.new
  end

  # GET /atrativos/1/edit
  def edit
  end

  # POST /atrativos
  # POST /atrativos.json
  def create
    @atrativo = Atrativo.new(atrativo_params)
    @atrativo.pessoa_juridica = current_user.pessoa_juridica

    respond_to do |format|
      if @atrativo.save
        flash[:success] = 'Atrativo criado com sucesso!'
        format.html { redirect_to @atrativo }
        format.json { render :show, status: :created, location: @atrativo }
      else
        format.html { render :new }
        format.json { render json: @atrativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atrativos/1
  # PATCH/PUT /atrativos/1.json
  def update
    respond_to do |format|
      if @atrativo.update(atrativo_params)
        format.html { redirect_to @atrativo, notice: 'Atrativo was successfully updated.' }
        format.json { render :show, status: :ok, location: @atrativo }
      else
        format.html { render :edit }
        format.json { render json: @atrativo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atrativos/1
  # DELETE /atrativos/1.json
  def destroy
    @atrativo.destroy
    respond_to do |format|
      flash[:info] = 'Atrativo removido com sucesso!'
      format.html { redirect_to atrativos_url}
      format.json { head :no_content }
    end
  end

  def cadastrar_entradas
    @atrativo = Atrativo.find(params[:atrativo_id])

    if not user_has_permission_to_access_atrativo(@atrativo, current_user)
      render :file => "public/401.html", :status => :unauthorized
    end

    registro_venda_ingressos = RegistroVendaIngressos.new
    registro_venda_ingressos.valorIngressoCriancaCentavos = @atrativo.valorIngressoCriancaCentavos
    registro_venda_ingressos.valorIngressoAdultoCentavos = @atrativo.valorIngressoAdultoCentavos
    registro_venda_ingressos.numeroAdultos = params[:numeroAdultos]
    registro_venda_ingressos.numeroCriancas = params[:numeroCriancas]
    registro_venda_ingressos.atrativo = @atrativo

    respond_to do |format|
      if registro_venda_ingressos.save
        flash[:success] = 'Venda de ingressos registrada com sucesso!'
      else
        flash[:error] = registro_venda_ingressos.errors.messages
      end

      format.html { redirect_to @atrativo }
    end
  end

  private
    def user_has_permission_to_access_atrativo(atrativo, user)
      return atrativo.pessoa_juridica_id == user.pessoa_juridica_id
    end

    def set_atrativo
      @atrativo = Atrativo.find(params[:id])

      if not user_has_permission_to_access_atrativo(@atrativo, current_user)
        render :file => "public/401.html", :status => :unauthorized
      end
    end

    def check_admin_access
      if not current_user.admin
        render :file => "public/401.html", :status => :unauthorized
      end
    end

    # Never trust parameters from the scary internet, only alvalorIngressoAdultolow the white list through.
    def atrativo_params
      params_atrativo = params.require(:atrativo).permit(:nome, :endereco, :tempoDuracaoMinutos, :capacidadeMaximaPessoas,
                                       :valorIngressoAdultoCentavos, :valorIngressoCriancaCentavos, :imagem)

      params_atrativo['valorIngressoAdultoCentavos'].gsub! ',', ''
      params_atrativo['valorIngressoCriancaCentavos'].gsub! ',', ''

      params_atrativo
    end
end

app/helpers/atrativos_helper.rb
module AtrativosHelper
end

app/views/atrativos/_form.html.erb
<style>
  .mdl-button--file input {
    cursor: pointer;
    height: 100%;
    right: 0;
    opacity: 0;
    position: absolute;
    top: 0;
    width: 300px;
    z-index: 4;
  }

  .mdl-textfield--file .mdl-textfield__input {
    box-sizing: border-box;
    width: calc(100% - 32px);
  }

  .mdl-textfield--file .mdl-button--file {
    right: 0;
  }
</style>

<div class="mdl-cell mdl-cell--12-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop mdl-card mdl-shadow--4dp" style="margin-top: 50px;
    margin-bottom: 50px;">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text"><%= action %> Atrativo</h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_with(model: atrativo, local: true) do |form| %>
      <% if atrativo.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(atrativo.errors.count, "error") %> prohibited this atrativo from being saved:</h4>

          <ul>
            <% atrativo.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <label>Imagem</label>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--file">
        <input class="mdl-textfield__input" placeholder="Imagem" required='true' type="text" id="uploadFile" readonly value="<%= atrativo.imagem.attached? ? atrativo.imagem&.filename : '' %>"/>
        <div class="mdl-button mdl-button--primary mdl-button--icon mdl-button--file">
          <i class="material-icons">attach_file</i><%= form.file_field :imagem, id: 'uploadBtn' %>
        </div>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :nome, {class: 'mdl-textfield__input', required: ''} %>
        <label class="mdl-textfield__label">Nome</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :endereco, {class: 'mdl-textfield__input', required: true} %>
        <label class="mdl-textfield__label">Endereço</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :tempoDuracaoMinutos, {class: 'mdl-textfield__input', type: 'number', required: ''} %>
        <label class="mdl-textfield__label">Tempo de Duração (minutos)</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :capacidadeMaximaPessoas, {class: 'mdl-textfield__input', type: 'number', required: ''} %>
        <label class="mdl-textfield__label">Capacidade máxima de pessoas</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :valorIngressoAdultoCentavos, {class: 'mdl-textfield__input money', required: ''} %>
        <label class="mdl-textfield__label">Valor do ingresso para adulto (R$)</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :valorIngressoCriancaCentavos, {class: 'mdl-textfield__input money', required: true} %>
        <label class="mdl-textfield__label">Valor do ingresso para criança (R$)</label>
      </div>

      <p>
        <%= link_to "<i class='mdl-color-text--white-400 material-icons'>arrow_back</i> Voltar".html_safe, atrativos_path, {class: "mdl-button mdl-js-button mdl-button--raised mdl-button--primary"} %>
        <button style="float: right" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
          Cadastrar
        </button>
      </p>
    <% end %>
  </div>

  <script>
    $(function () {
        document.getElementById("uploadBtn").onchange = function () {
            document.getElementById("uploadFile").value = this.files[0].name;
        };
    });
  </script>
</div>

app/views/atrativos/edit.html.erb
<%= render 'form', atrativo: @atrativo, action: 'Editar' %>

<%= link_to 'Back', atrativos_path %>

app/views/atrativos/index.html.erb
<style>
  .demo-card-wide {
    margin-bottom: 25px;
  }

  .demo-card-wide > .mdl-card__title {
    color: #fff;
    height: 176px;
    /*background: url('https://getmdl.io/assets/demos/welcome_card.jpg') center / cover;*/
  }

  .info-list-atrativos {
    margin: 0;
    padding-left: 20px;
  }

    .atrativo-title {
      color: white;
      background-color: #ff4081;
      border-radius: 10px;
      padding-left: 10px;
      padding-right: 10px;
      padding-top: 7px;
      padding-bottom: 7px;
      font-weight: 500;
    }
</style>

<div class="mdl-cell mdl-cell--12-col" style="margin-bottom: 50px;">
  <div style="text-align: center">
    <h3>Lista de Atrativos</h3>
    <h4>Pessoa Jurídica: <%= @pessoa_juridica.nome_fantasia %></h4>
  </div>

  <div class="mdl-grid" style="display: flex; justify-content: space-around;">
    <% if @atrativos.length > 0%>
      <% @atrativos.each do |atrativo| %>
        <div class="mdl-cell--6-col demo-card-wide mdl-card mdl-shadow--2dp">
          <div class="mdl-card__title" style="background: url('<%= atrativo.imagem.attached? ? url_for(atrativo.imagem) : image_url('imagePlaceholder.png') %>') center / cover">
            <h2 class="mdl-card__title-text atrativo-title mdl-shadow--8dp">
              <%= atrativo.nome %></h2>
          </div>
          <div class="mdl-card__supporting-text">
            <ul class="info-list-atrativos">
              <li>Endereço: <%= atrativo.endereco %></li>
              <li>Tempo de Duração: <%= atrativo.tempoDuracaoMinutos %> min</li>
              <li>Capacidade Máxima de Pessoas: <%= atrativo.capacidadeMaximaPessoas %></li>
            </ul>
          </div>
          <div class="mdl-card__actions mdl-card--border" style="display: flex; justify-content: space-around;">
            <%= link_to "<i class='mdl-color-text--blue-grey-400 material-icons'>remove_red_eye</i> Visualizar".html_safe, atrativo, {class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"} %>
            <%= link_to "<i class='mdl-color-text--blue-grey-400 material-icons'>edit</i> Editar".html_safe, edit_atrativo_path(atrativo), {class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"} %>

            <% if current_user.admin %>
              <%= link_to "<i class='mdl-color-text--blue-grey-400 material-icons'>delete</i> Remover".html_safe, atrativo, method: :delete, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect", data: { confirm: 'Você tem certeza?' } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="mdl-cell mdl-cell--12-col">
        <div class="alert alert-info">
          Nenhum atrativo foi cadastrado para essa pessoa jurídica.
        </div>
      </div>
    <% end %>

    <% if current_user.admin %>
      <div class="mdl-cell mdl-cell--12-col" style="text-align: center">
        <%= link_to 'Criar Atrativo', new_atrativo_path, {class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/atrativos/new.html.erb
<%= render 'form', atrativo: @atrativo, action: 'Criar' %>

<%= link_to 'Back', atrativos_path %>

app/views/atrativos/show.html.erb
<style>
  .demo-card-wide {
    margin-bottom: 25px;
  }

  .demo-card-wide > .mdl-card__title {
    color: #fff;
    height: 300px;
    justify-content: center;
  }

  .info-list-atrativos {
    margin: 0;
    padding-left: 20px;
  }

  .atrativo-title {
    color: white;
    background-color: #ff4081;
    border-radius: 10px;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 7px;
    padding-bottom: 7px;
    font-weight: 500;
    align-self: flex-start !important;
    font-size: 30px;

  }

  .mdl-card {
    min-height: 0px !important;
  }

  .atrativo-entrada-card {
    text-align: center;
    padding: 10px;
  }

  .atrativo-entrada-card p {
    font-size: 19px;
  }
    .atrativo-entrada-card h5 {
      font-size: 19px;
    }
</style>

<div class="mdl-cell mdl-cell--12-col" style="margin-bottom: 50px;">
  <div class="mdl-grid" style="display: flex; justify-content: space-around;">
    <div class="mdl-cell--12-col demo-card-wide mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title" style="background: url('<%= @atrativo.imagem.attached? ? url_for(@atrativo.imagem) : image_url('imagePlaceholder.png') %>') center / cover">
        <h2 class="mdl-card__title-text atrativo-title mdl-shadow--8dp">
          <%= @atrativo.nome %></h2>
      </div>
      <div class="mdl-card__supporting-text">
        <ul class="info-list-atrativos">
          <li> Endereço: <%= @atrativo.endereco %></li>
          <li>Tempo de Duração: <%= @atrativo.tempoDuracaoMinutos %> min</li>
          <li>Capacidade Máxima de Pessoas: <%= @atrativo.capacidadeMaximaPessoas %></li>
          <li>Valor do Ingresso para Criança: R$ <%= @atrativo.valor_ingresso_crianca %></li>
          <li>Valor do Ingresso para Adulto: R$ <%= @atrativo.valor_ingresso_adulto %></li>
        </ul>
      </div>
    </div>

    <div class="mdl-cell--12-col mdl-card mdl-shadow--2dp mdl-grid" style="margin-bottom: 20px">
      <div class="mdl-cell mdl-cell--4-col mdl-cell--3-col-desktop atrativo-entrada-card">
        <h5>Nº de pessoas no mês </h5>
        <p><%= @atrativo.get_numero_ingressos_vendidos(true) %></p>
      </div>
      <div class="mdl-cell mdl-cell--4-col mdl-cell--3-col-desktop atrativo-entrada-card">
        <h5>Valor total arrecadado no mês</h5>
        <p>R$ <%= @atrativo.valor_total_arrecadado(true) %></p>
      </div>
      <div class="mdl-cell mdl-cell--4-col mdl-cell--3-col-desktop atrativo-entrada-card">
        <h5>Número total de pessoas</h5>
        <p><%= @atrativo.get_numero_ingressos_vendidos %></p>
      </div>
      <div class="mdl-cell mdl-cell--4-col mdl-cell--3-col-desktop atrativo-entrada-card">
        <h5>Valor total arrecadado</h5>
        <p>R$ <%= @atrativo.valor_total_arrecadado %></p>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col" style="text-align: center">
      <%= link_to "<i class='mdl-color-text--white-400 material-icons'>arrow_back</i> Voltar".html_safe, atrativos_path, {class: "mdl-button mdl-js-button mdl-button--raised mdl-button--primary"} %>
      <%= link_to "<i class='mdl-color-text--white-400 material-icons'>edit</i> Editar".html_safe, edit_atrativo_path(@atrativo), {class: "mdl-button mdl-js-button mdl-button--raised mdl-button--primary"} %>
      <% if current_user.admin %>
        <%= link_to "<i class='mdl-color-text--white-400 material-icons'>delete</i> Remover".html_safe, @atrativo, method: :delete, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--primary", data: {confirm: 'Você tem certeza?'} %>
      <% end %>
      <button id="show-dialog" type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-button--primary">
        <i class='mdl-color-text--white-400 material-icons'>attach_money</i> Cadastrar Entradas
      </button>

    </div>

    <dialog class="mdl-dialog">
      <h4 class="mdl-dialog__title">Venda de Ingressos</h4>
      <div class="mdl-dialog__content">
        <%= form_tag(atrativo_cadastrar_entradas_path(@atrativo), method: "post", id: 'formVendaIngressos') do %>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <input type="number" class="mdl-textfield__input" required name="numeroAdultos">
            <label class="mdl-textfield__label">Número de adultos</label>
          </div>

          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <input type="number" class="mdl-textfield__input" required name="numeroCriancas">
            <label class="mdl-textfield__label">Número de crianças</label>
          </div>
      </div>
      <div class="mdl-dialog__actions">
        <button type="submit" class="mdl-button" form="formVendaIngressos">Cadastrar</button>
        <button type="button" class="mdl-button close">Cancelar</button>
      </div>

      <% end %>

      </dialog>
    <script>
        var dialog = document.querySelector('dialog');
        var showDialogButton = document.querySelector('#show-dialog');
        if (!dialog.showModal) {
            dialogPolyfill.registerDialog(dialog);
        }
        showDialogButton.addEventListener('click', function () {
            dialog.showModal();
        });
        dialog.querySelector('.close').addEventListener('click', function () {
            dialog.close();
        });
    </script>
  </div>
</div>