config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_out: 'logout'}

  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :pessoa_juridicas
  resources :atrativos do
    post 'cadastrar_entradas'
  end
  resources :funcionarios do
    get 'toggleActiveStatus', on: :member
  end

end

app/models/pessoa_juridica.rb
class PessoaJuridica < ApplicationRecord
  has_one :user
  has_many :atrativos
  has_many :funcionarios

  # We will save the field 'cnpj' with the mask on it. So the length is 18 with the mask, and 14 without it.
  validates :cnpj, presence: true, length: { is: 18 }, uniqueness: true
  validates :razao_social, presence: true
  validates :nome_fantasia, presence: true
end

app/controllers/pessoa_juridicas_controller.rb
class PessoaJuridicasController < ApplicationController
  before_action :set_pessoa_juridica, only: [:show, :edit, :update, :destroy]

  # GET /pessoa_juridicas
  # GET /pessoa_juridicas.json
  def index
    @pessoa_juridicas = PessoaJuridica.all
  end

  # GET /pessoa_juridicas/1
  # GET /pessoa_juridicas/1.json
  def show
  end

  # GET /pessoa_juridicas/new
  def new
    @pessoa_juridica = PessoaJuridica.new
  end

  # GET /pessoa_juridicas/1/edit
  def edit
  end

  # POST /pessoa_juridicas
  def create
    @pessoa_juridica = PessoaJuridica.new(pessoa_juridica_params)
    # @user = User.new(usuario_pessoa_juridica_params)
    #
    if @pessoa_juridica.save
      @user = @pessoa_juridica.create_user(usuario_pessoa_juridica_params)

      if @user.valid?
        flash[:success] = "Cadastro realizado com sucesso."
        redirect_to :controller => 'welcome', :action => 'index'
      else
        @pessoa_juridica.destroy
        render 'new'
      end
    else
      render 'new'
    end
  end

  # PATCH/PUT /pessoa_juridicas/1
  # PATCH/PUT /pessoa_juridicas/1.json
  def update
    respond_to do |format|
      if @pessoa_juridica.update(pessoa_juridica_params)
        format.html { redirect_to @pessoa_juridica, notice: 'Pessoa juridica was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa_juridica }
      else
        format.html { render :edit }
        format.json { render json: @pessoa_juridica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoa_juridicas/1
  # DELETE /pessoa_juridicas/1.json
  def destroy
    @pessoa_juridica.destroy
    respond_to do |format|
      format.html { redirect_to pessoa_juridicas_url, notice: 'Pessoa juridica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa_juridica
      @pessoa_juridica = PessoaJuridica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_juridica_params
      params.require(:pessoa_juridica).permit(:cnpj, :razao_social, :nome_fantasia)
    end

    def usuario_pessoa_juridica_params
      user_params = params.require(:pessoa_juridica).permit(:email, :password)

      user_params['admin'] = true
      user_params['active'] = true

      user_params
    end
end

app/helpers/pessoa_juridicas_helper.rb
module PessoaJuridicasHelper
end

app/views/pessoa_juridicas/_form.html.erb
<%= form_with(model: pessoa_juridica, local: true) do |form| %>
  <% if pessoa_juridica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa_juridica.errors.count, "error") %> prohibited this pessoa_juridica from being saved:</h2>

      <ul>
      <% pessoa_juridica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoa_juridicas/edit.html.erb
<h1>Editing Pessoa Juridica</h1>

<%= render 'form', pessoa_juridica: @pessoa_juridica %>

<%= link_to 'Show', @pessoa_juridica %> |
<%= link_to 'Back', pessoa_juridicas_path %>

app/views/pessoa_juridicas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoa Juridicas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoa_juridicas.each do |pessoa_juridica| %>
      <tr>
        <td><%= link_to 'Show', pessoa_juridica %></td>
        <td><%= link_to 'Edit', edit_pessoa_juridica_path(pessoa_juridica) %></td>
        <td><%= link_to 'Destroy', pessoa_juridica, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa Juridica', new_pessoa_juridica_path %>

app/views/pessoa_juridicas/new.html.erb
<div class="mdl-cell mdl-cell--12-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop mdl-card mdl-shadow--4dp" style="margin-top: 50px;
    margin-bottom: 50px;">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Cadastrar Pessoa Jurídica</h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_with(model: @pessoa_juridica, local: true) do |form| %>
      <% if @pessoa_juridica.errors.any? %>
        <div id="error_explanation">
          <h4>Encontrou-se <%= pluralize(@pessoa_juridica.errors.count, "erros") %> ao tentar realizar o cadastro:</h4>

          <ul>
            <% @pessoa_juridica.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @user&.errors&.any? %>
        <div id="error_explanation">
          <h4>Encontrou-se <%= pluralize(@user.errors.count, "erros") %> ao tentar realizar o cadastro:</h4>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :cnpj, {class: 'mdl-textfield__input cnpj'} %>
        <label class="mdl-textfield__label" for="cnpj">CNPJ</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :razao_social, {class: 'mdl-textfield__input'} %>
        <label class="mdl-textfield__label" for="razaoSocial">Razão Social</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :nome_fantasia, {class: 'mdl-textfield__input'} %>
        <label class="mdl-textfield__label" for="nomeFantasia">Nome Fantasia</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :email, {class: 'mdl-textfield__input', type: 'email'} %>
        <label class="mdl-textfield__label" for="email">E-mail</label>
        <span class="mdl-textfield__error">Insira um e-mail válido</span>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :password, {class: 'mdl-textfield__input', type: 'password', minlength: 6} %>
<!--        <input class="mdl-textfield__input" type="password" id="password">-->
        <label class="mdl-textfield__label" for="password">Senha</label>
        <span class="mdl-textfield__error">Insira um senha com no mínimo 6 caracteres</span>
      </div>
      <p>
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
          Cadastrar
        </button>
      </p>

      <!--<div class="actions">
        <%#= form.submit %>
      </div>-->
    <% end %>
  </div>
</div>

<%#= render 'form', pessoa_juridica: @pessoa_juridica %>

app/views/pessoa_juridicas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pessoa_juridica_path(@pessoa_juridica) %> |
<%= link_to 'Back', pessoa_juridicas_path %>