config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_out: 'logout'}

  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :pessoa_juridicas
  resources :atrativos do
    post 'cadastrar_entradas'
  end
  resources :funcionarios do
    get 'toggleActiveStatus', on: :member
  end

end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  belongs_to :user
  belongs_to :pessoa_juridica

  validates :nome, presence: true
  validates :cpf, presence: true, length: { is: 14 }, uniqueness: true
  validates :cargo, presence: true
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy, :toggleActiveStatus]
  before_action :check_admin_access

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    puts 'index'

    @pessoa_juridica = current_user.pessoa_juridica

    @funcionarios = @pessoa_juridica.funcionarios
  end

  def toggleActiveStatus
    user = @funcionario.user
    user.active = !user.active
    user.save

    flash[:info] = "Usuário atualizado com sucesso."
    redirect_to action: 'index'
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  def create
    @funcionario = Funcionario.new(funcionario_params)
    @funcionario.pessoa_juridica = current_user.pessoa_juridica
    @user = @funcionario.create_user(funcionario_user_params)

    respond_to do |format|
      if @funcionario.save
        @user = @funcionario.create_user(funcionario_user_params)
        @user.admin = false
        @user.active = true
        @user.pessoa_juridica = current_user.pessoa_juridica

        if @user.valid?
          @user.save

          @funcionario.user = @user
          @funcionario.save

          flash[:success] = "Cadastro realizado com sucesso."
          format.html { redirect_to funcionarios_path }
        else
          @funcionario.destroy
          format.html { render :new }
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    def check_admin_access
      if not current_user.admin
        render :file => "public/401.html", :status => :unauthorized
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :cargo)
    end

    def funcionario_user_params
      params.require(:funcionario).permit(:email, :password)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<div class="mdl-cell mdl-cell--12-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop mdl-card mdl-shadow--4dp" style="margin-top: 50px;
    margin-bottom: 50px;">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text"><%= action %> Funcionário</h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_with(model: funcionario, local: true) do |form| %>
      <% if funcionario.errors.any? %>
        <div id="error_explanation">
          <h4>Encontrou-se <%= pluralize(funcionario.errors.count, "erros") %> ao tentar realizar o cadastro:</h4>

          <ul>
            <% funcionario.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @user&.errors&.any? %>
        <div id="error_explanation">
          <h4>Encontrou-se <%= pluralize(@user.errors.count, "erros") %> ao tentar realizar o cadastro:</h4>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :nome, {class: 'mdl-textfield__input', required: true} %>
        <label class="mdl-textfield__label">Nome</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :cpf, {class: 'mdl-textfield__input cpf', required: true} %>
        <label class="mdl-textfield__label">CPF</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :cargo, {class: 'mdl-textfield__input', required: true} %>
        <label class="mdl-textfield__label">Cargo</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :email, {class: 'mdl-textfield__input', type: 'email', required: true} %>
        <label class="mdl-textfield__label" for="email">E-mail</label>
        <span class="mdl-textfield__error">Insira um e-mail válido</span>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :password, {class: 'mdl-textfield__input', type: 'password', minlength: 6, required: true} %>
        <label class="mdl-textfield__label" for="password">Senha</label>
        <span class="mdl-textfield__error">Insira um senha com no mínimo 6 caracteres</span>
      </div>

      <p>
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
          Cadastrar
        </button>
      </p>

    <% end %>
  </div>
</div>

app/views/funcionarios/edit.html.erb
<%= render 'form', funcionario: @funcionario, action: 'Editar' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<style>
  table th {
    text-align: center!important;
  }
</style>

<div class="mdl-cell mdl-cell--12-col" style="margin-bottom: 50px;">
  <div style="text-align: center">
    <h3>Lista de Funcionários</h3>
    <h4>Pessoa Jurídica: <%= @pessoa_juridica.nome_fantasia %></h4>
  </div>

  <div class="mdl-cell mdl-cell--12-col" style="display: flex; justify-content: center">
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
      <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Cargo</th>
        <th>E-mail</th>
        <th>Status</th>
        <th>Ações</th>
      </tr>
      </thead>
      <tbody>
      <% if @funcionarios.length > 0%>
        <% @funcionarios.each do |funcionario| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= funcionario.nome %></td>
            <td><%= funcionario.cpf %></td>
            <td><%= funcionario.cargo %></td>
            <td><%= funcionario.user.email %></td>
            <td><%= funcionario.user.active ? 'Ativo' : 'Desativado' %></td>
            <td>
              <% if funcionario.user.active %>
                <%= link_to "<i class='mdl-color-text--blue-grey-400 material-icons'>highlight_off</i> Desativar".html_safe, toggleActiveStatus_funcionario_path(funcionario), {class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect", data: {confirm: 'Você tem certeza que deseja desativar esse usuário?'}} %>
              <% else %>
                <%= link_to "<i class='mdl-color-text--blue-grey-400 material-icons'>check_circle_outline</i> Ativar".html_safe, toggleActiveStatus_funcionario_path(funcionario), {class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect", data: {confirm: 'Você tem certeza que deseja ativar esse usuário?'}} %>
            <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="6">
            <p style="margin-top: 15px;">Nenhum funcionário foi cadastrado para essa pessoa jurídica. Clique no botão abaixo para criar um novo funcionário.</p>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <div class="mdl-cell mdl-cell--12-col" style="text-align: center">
    <%= link_to 'Criar Funcionário', new_funcionario_path, {class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent'} %>
  </div>


</div>

app/views/funcionarios/new.html.erb
<%= render 'form', funcionario: @funcionario, action: 'Criar' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>