config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_out: 'logout'}

  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :pessoa_juridicas
  resources :atrativos do
    post 'cadastrar_entradas'
  end
  resources :funcionarios do
    get 'toggleActiveStatus', on: :member
  end

end

app/views/layouts/_feedbackMessages.html.erb
<% if flash[:error] %>
  <div class="mdl-cell mdl-cell--12-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop">
    <div class="alert alert-danger"><%= flash[:error] %></div>
  </div>
<% end %>

<% if flash[:success] %>
  <div class="mdl-cell mdl-cell--12-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop">
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
  </div>
<% end %>

<% if flash[:info] %>
  <div class="mdl-cell mdl-cell--12-col-tablet mdl-cell--8-col-desktop mdl-cell--2-offset-desktop">
    <div class="alert alert-info"><%= flash[:info] %></div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">Atrativos Bonitour</div>
  </div>
  <div class="mdl-mini-footer__right-section">
    <ul class="mdl-mini-footer__link-list">
      <li>Alessandro Costa, 2018</li>
    </ul>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
  <% if user_signed_in? %>
    <%= link_to('Atrativos', atrativos_path, {class: "mdl-navigation__link " + current_class_logged_area?(atrativos_path)}) %>
    <% if current_user.admin %>
      <%= link_to('Funcionários', funcionarios_path, {class: "mdl-navigation__link " + current_class_logged_area?(funcionarios_path)}) %>
    <% end %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link") %>
  <% else %>
    <%= link_to "Logar", welcome_index_path, {class: "mdl-navigation__link " + current_class_public_area?(welcome_index_path)} %>
    <%= link_to "Cadastrar", new_pessoa_juridica_path, {class: "mdl-navigation__link " + current_class_public_area?(new_pessoa_juridica_path)} %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<!--
  Material Design Lite
  Copyright 2015 Google Inc. All rights reserved.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License
-->
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="A portfolio template that uses Material Design Lite.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <title>Atrativos Bonitour</title>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<!--  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-pink.min.css"/>-->

  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.deep_orange-green.min.css" />

  <style>
    .mdl-layout {
      height: auto;
    }
  </style>

  <script>
      $( document ).on('turbolinks:load', function() {
          componentHandler.upgradeAllRegistered();
      })
  </script>

</head>

<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header mdl-layout__header--waterfall portfolio-header">
    <div class="mdl-layout__header-row portfolio-logo-row">
                <span class="mdl-layout__title" style="width: 350px">
                    <div class="portfolio-logo"></div>
                    <span class="mdl-layout__title" style="color: #20a551; font-size: 32px; font-weight: bolder;">Atrativos <span style="color: #f0811f">Bonitour</span></span>
                </span>
    </div>
    <div class="mdl-layout__header-row portfolio-navigation-row mdl-layout--large-screen-only">
      <%= render "layouts/menu" %>
    </div>
  </header>
  <div class="mdl-layout__drawer mdl-layout--small-screen-only">
    <%= render "layouts/menu" %>
  </div>

  <main class="mdl-layout__content">
    <div class="mdl-grid portfolio-max-width portfolio-contact">
      <%= render "layouts/feedbackMessages" %>

      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </main>
</div>
</body>

</html>